echo ""
echo "Crunch Commands"
echo "Shell scripts that perform common command sequences. See documentation link for more information."
echo "Documentation: https://github.com/sumtype/crunch-commands"
echo ""
echo "'crunch-commmands' is a command used to perform tasks related to the crunch-commands package.  You can use the following commands after 'crunch-commands' to perform various actions:"
echo ""
echo "    update"
echo "      -Updates the crunch-commands package and adds them to your ~/.bashrc file.  Restart terminal the afterwards."
echo "      -Example: 'crunch-commands update'"
echo ""
echo "    help"
echo "      -Displays the help menu you're looking at right now."
echo "      -Example: 'crunch-commands help'"
echo ""
